### ISSUE TITLE
Disable Disconnect?

### ISSUE THREAD

**Issue by chadcarlton** [MSOpenTech/moodle-auth_oidc#4]
Is it possible to create a admin panel toggle for Manage/Disconnect capabilities?  I.e. If an organization has decided to only use AAD for authentication, then this disconnect option does not make sense or could be used to continue to have access to moodle after an AAD account has been disabled.

**Comment by jamesmcq** [comment]
The auth/oidc:manageconnection capability controls access to the OpenID Connect management page, so removing this capability can be used to prevent users switching away from OpenID Connect. There is still a "disconnect" option present in the Office365 Connection Management page, however this just removes the user's stored Office365 tokens - it does not change any other user information, including login method.

**Comment by chadcarlton** [comment]
I'm sorry I must be missing it in the myriad of menus, where is the "manageconnection" capability, and how can I remove/toggle it?

**Comment by chadcarlton** [comment]
I was able to test this with a non admin user, and I understand now. an admin user can render the disconnect link.
