### ISSUE TITLE
failed upgrade

### ISSUE THREAD

**Issue by leonhedding** [MSOpenTech/moodle-auth_oidc#5]
Upon upgrading from Moodle 2.7.7 to 2.9.1 I updated auth_oidc as well. The upgrade failed with the following error message.

Debug info: ERROR: syntax error at or near "." at character 12
SELECT user.id as userid,
user.username as username,
tok.id as tokenid,
tok.oidcuniqid as oidcuniqid,
tok.idtoken as idtoken
FROM mdl_auth_oidc_token as tok
JOIN mdl_user user ON user.username = tok.username
WHERE user.auth = $1 AND deleted = 0
[array (
0 => 'oidc',
)]
Error code: dmlreadexception

We are running PGSQL if that makes any difference instead of MySQL.

**Comment by jamesmcq** [comment]
Thanks Leon, I think PGSQL is the issue here - I develop and test with MySQL and try to maintain compatibility with PG but sometimes these issues crop up. I've put this issue into the list of bugs to be fixed for an upcoming release.

**Comment by leonhedding** [comment]
Ok, Thanks. Do you have any suggestions for how to get the upgrade to succeed? Do I uninstall the plugin and all the dependencies until there is an upcoming release?

**Comment by jamesmcq** [comment]
Hi Leon, yes until the you have the new version uninstalling would get the update to complete. How are you installing the plugins? Through Git/Github? Moodle plugin database?

**Comment by leonhedding** [comment]
Download it from the Moodle plugin database. In the end I manually ran the SQL queries in pgsql just so that I could complete my upgrade of Moodle which I had done at the same time as the upgrade of the plugin.
